const blogs = [
    {
        id: 1,
        image: "./img/blog01.png",
        title: "Tips for Excelling in Distance Learning",
        author: "Matthew Palabrica",
        content: "With the pandemic still showing no signs of ending, students are left with no choice but to endure more months of distance learning. While this has been a difficult challenge for a lot of children across the country, it remains the most feasible option given the current situation. Students who have struggled with distance learning must take steps to alleviate the difficult circumstances and succeed even in these trying times because, if it wasn’t obvious before, distance learning is a wholly different challenge to physical classes.\n With that, here are several things each student should practice in order to ace distance learning. Note that while these may not necessarily solve the problem of economic problems, they can most certainly ease them to an extent.\n The first is to practice self-discipline. In distance learning, students are required to learn mostly by themselves. They will not be supervised by their teacher most of the time. Now, while students may feel like this is a good thing at first, this can be a challenge for them in the long run. Being stuck at home, the temptation of slacking, sleeping, cramming, and getting themselves distracted can be a huge obstacle to them excelling. They must be able to strictly stay awake, allot enough time for their studies, and avoid distractions as much as they can.\n Next, students must also practice time management. This is something that’s related to the first tip. A key component of self-discipline is to be able to manage your time well. This involves prioritizing your workload and giving yourself enough time to finish it, while also allowing yourself to rest so that you’re able to preserve your physical, mental, and emotional well-being. To be able to balance both is a challenge, but if done right, it is a significant step towards being a successful student. \n Finally, students must learn to be independent. As previously mentioned, there are no teachers physically present to supervise students and guide them through their learning materials. Parents, while always willing to help their children, will not always be available to assist them. They must be able to learn on their own.\n With these three tips in mind, students should be able to maximize their potential and capabilities in under such difficult circumstances. Furthermore, these three are important traits when it comes to individual growth. So having children practice them from an early age wouldn’t be too bad.",
    },
    {
        id: 2,
        image: "./img/blog02.png",
        title:"Will the Massive Spike in CoViD-19 Infections Impact Learning in the Long Run?",
        author: "Matthew Palabrica",
        content: "With the pandemic still showing no signs of ending, students are left with no choice but to endure more months of distance learning. While this has been a difficult challenge for a lot of children across the country, it remains the most feasible option given the current situation. Students who have struggled with distance learning must take steps to alleviate the difficult circumstances and succeed even in these trying times because, if it wasn’t obvious before, distance learning is a wholly different challenge to physical classes. \n With that, here are several things each student should practice in order to ace distance learning. Note that while these may not necessarily solve the problem of economic problems, they can most certainly ease them to an extent. \n The first is to practice self-discipline. In distance learning, students are required to learn mostly by themselves. They will not be supervised by their teacher most of the time. Now, while students may feel like this is a good thing at first, this can be a challenge for them in the long run. Being stuck at home, the temptation of slacking, sleeping, cramming, and getting themselves distracted can be a huge obstacle to them excelling. They must be able to strictly stay awake, allot enough time for their studies, and avoid distractions as much as they can. \n Next, students must also practice time management. This is something that’s related to the first tip. A key component of self-discipline is to be able to manage your time well. This involves prioritizing your workload and giving yourself enough time to finish it, while also allowing yourself to rest so that you’re able to preserve your physical, mental, and emotional well-being. To be able to balance both is a challenge, but if done right, it is a significant step towards being a successful student. \n Finally, students must learn to be independent. As previously mentioned, there are no teachers physically present to supervise students and guide them through their learning materials. Parents, while always willing to help their children, will not always be available to assist them. They must be able to learn on their own. \n With these three tips in mind, students should be able to maximize their potential and capabilities in under such difficult circumstances. Furthermore, these three are important traits when it comes to individual growth. So having children practice them from an early age wouldn’t be too bad."
    },
    {
        id: 3,
        image: "./img/blog03.png",
        title: "Toys: Outdated or Not?",
        author: "Matthew Palabrica",
        content: "Today’s children have been buying less and less toys than ever before. It has been a noticeable trend that today’s young parents had a significantly larger toy collection compared to before. If you’ve also noticed this, then you’ve probably deduced that this has been a result of the emergence of electronic gadgets such as smartphones, tablets, and laptops. These gadgets, which have become more and more accessible to the general public over the last decade or so, have so many functions that children find enjoyable. They can play games, watch videos, and read from these gadgets. So it is no wonder that their emergence has almost rendered toys obsolete.\n However, toys have uses that can also be found in these gadgets. They allow a child to explore their imagination, for example. Also, some toys, like Lego blocks, give children the chance to develop their own creative skills by giving them a medium to construct any structure their young imaginations can conjure up. Furthermore, some toys, like balls and bikes, keep children active and healthy, while also improving their motor skills.\n A lot of young parents still have their toys. We are aware that the transition to electronic gadgets  is already at a stage where we can say that it’s inevitable. However, it wouldn’t hurt to introduce the kids to some toys, so to the parents, maybe you should dust them off and give them to their children. Allow your electronics to rest."
    },
    {
        id: 4,
        image: "/img/blog04.png",
        title: "Passion learning: What is it?",
        author: "Matthew Palabrica",
        content: " In our last article, we gave you guys a short intro on supplemental learning. We now know how it should be considered an option for those of you who can access it. It’s highly recommended for children who are bored, and for parents who want their children to stay productive. \n Now in line with that, we are introducing you to a fun little bit of supplemental learning. We’re gonna call this one, passion learning. Passion learning is using the things you love as an opportunity to increase your knowledge. Taking something you’re passionate about and turning it into a way to grow. It sounds like something too good to be true. But, with the countless options given to us by technology right now, we assure you, it very much exists.\n A prime example of this is video games. Video games have been perceived as detrimental for a child’s growth for the longest time. However, recent advancements in game content have exposed players to more learning opportunities while playing at the same time. Minecraft, for example, is a game that a lot of kids have been playing right now. The game, which lets players create their own world and structures, using blocks, has been praised for allowing its players to express their creative juices. Minecraft has also been used by several competitions as a medium for making creative and innovative structures. Truly, games like this are no longer the “wastes of time” we perceived them to be."
    }
]

export default blogs