import { Container } from '../../style';

const HowToPrepareFirstClass = () => {
  return (
    <Container>
      <h3>5 steps to help you and your learners have a great first class on </h3>
      <p>
        To set your learners up for the best possible first class experience, follow these
        5 simple steps:
      </p>
      <p>&nbsp;</p>
      <h3>Before Class:</h3>
      <p>
        <b>1. Watch This Quick Jitsi Tutorial</b>
      </p>
      <p>
        Before you start your class, please get acclimated with our video-chat meeting
        tool Jitsi. Learn{' '}
        <a
          href='https://www.youtube.com/watch?v=3Iwiwq7eofE'
          target='_blank'
          rel='noreferrer'
        >
          basic Jitsi controls
        </a>{' '}
        to help your learner connect with their teacher at Tagpros.
      </p>
      <p>
        <b>2. Practice our Jitsi Meeting Video-Chat Link</b>
      </p>
      <p>
        We encourage you to{' '}
        <a href='https://meet.jit.si/' target='_blank' rel='noreferrer'>
          Practice Using Jitsi
        </a>
        . You don’t need to set up a personal Jitsi account to access Tagpros classes as
        the link will be generated by our platform to you and your students.
      </p>
      <p>
        <b>3. Test Jitsi</b>
      </p>
      <p>
        Join a{' '}
        <a href='https://meet.jit.si/' target='_blank' rel='noreferrer'>
          test Jitsi
        </a>{' '}
        meeting with your learner to make sure Jitsi is working properly on your device.
      </p>
      <p>
        <b>Have your learner practice the following:</b>
      </p>
      <ul>
        <li>Turn off / turn on the microphone</li>
        <li>Turn off / turn on the video</li>
        <li>Click the 'Participants' button and use the 'raise hand' button</li>
        <li>Click the 'Chat' button and type 'hello!' into the chat box</li>
      </ul>
      <p>
        <b>4. Prepare for class</b>
      </p>
      <ul>
        <li>
          Review the{' '}
          <a href='/policies/tagpros-community/community-code-of-conduct' target='_blank'>
            Learner Code of Conduct
          </a>{' '}
          with your learner.
        </li>
        <li>
          Always check every learner’s identity before the class. This means seeing them
          via video or audio at least once every class. Tell all learners and parents that
          they should inform you if connecting through video is not possible. You should
          ask to confirm their identity or presence by speaking with the teacher usually
          before the online class start.
        </li>
        <li>
          Find a quiet place for your learner to attend the class that is not disruptive
          to the class or other learners.
        </li>
        <li>
          Make sure that any required materials are ready before class starts. Your
          teacher will let you know in the classroom if your learner needs to bring
          anything to class.
        </li>
      </ul>
      <h3>Five Minutes Before Class Starts…</h3>
      <p>
        <b>5. Go to the classroom</b>
      </p>
      <ul>
        <li>Log in at Tagpros</li>
        <li>Click "Schedule" </li>
        <li>Click on the class title</li>
        <li>Select the "classroom" tab</li>
        <li>Click the button that says "join meeting"</li>
      </ul>
      <p>
        If you see a message that says "Please wait for the host to start the meeting" -
        be patient! Your teacher will arrive soon! That's it! You're ready to start
        learning! 🎉
      </p>
      <p>&nbsp;</p>
      <h3>If you experience tech issues... </h3>
      <p>
        Check out our Jitsi’s comprehensive{' '}
        <a
          href='https://jitsi.github.io/handbook/docs/user-guide/'
          target='_blank'
          rel='noreferrer'
        >
          Jitsi Handbook
        </a>
      </p>
      <p>
        Note: teachers will do their best to assist you if you experience tech issues
        during class, but remember - their primary focus is on creating an excellent
        learning experience for all learners, so their ability to troubleshoot with
        individual families is limited.{' '}
      </p>
    </Container>
  );
};

export default HowToPrepareFirstClass;
